### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by ccbbzz** [ViviXiang/SocialCVAE#1]
您好！我是上海海洋大学的研究生，研究船舶轨迹预测的。非常感谢您的代码贡献，我有几个问题：
1、我发现数据集中masks文件夹，里面的场景图片为什么都是黑色的？
2、您对数据集进行了哪些预处理，我看原数据集有64G的。
非常感谢您的回答！

**Comment by ViviXiang** [comment]
1. mask 文件夹里的图片是分割图，每个像素的值都很小。
2. 有关数据集预处理过程，可以参考 baseline NSP-SFM (https://github.com/realcrane/Human-Trajectory-Prediction-via-Neural-Social-Physics.git)。

**Comment by ccbbzz** [comment]
非常感谢您的回复，我看出了那些图片
